config/routes.rb
Rails.application.routes.draw do
  get '/index' => 'pages#index'
  get '/about' => 'pages#about'
  get '/references' => 'pages#reference'
  get '/show/:id', to:  'pages#show', as: 'show_house'
  root 'pages#index'

  post 'contact', to: 'messages#create'
  get 'contact_error', to: 'messages#contact_error', as: 'contact_error'
  get 'contact_sent', to: 'messages#contact_sent', as: 'contact_sent'

  get "/admin" => 'houses#index'
  resources :houses
  
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
		has_secure_password
end

app/models/house.rb
class House < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	mount_uploaders :gallery, ImageUploader
	
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
            presence: { message: "Kérjük adja meg nevét" }
  validates_length_of :name, :within => 2..20, :message => "Kérjük valós nevet adjon meg"
  validates_format_of :name, :with => /\A[a-zA-ZÀÁÂÃÄÅàáâãäåÒÓÔÕÖŐØòóôõőöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ\s]+\z/, :message=> "Kérjük nevében csak betűket használjon"

  validates :email,
            presence: { message: "Kérjük adja meg az e-mail címét" }
  validates_format_of :email, :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, :message => "Kérjük valós e-mail címet adjon meg"

  validates :content,
            presence: { message: "Kérjük adja meg üzenetét" }
  validates_length_of :content, :within => 3..600, :message => "Üzenetének minimum 3 és maximum 600 karakterből kell állnia"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   helper_method :current_admin

def current_admin 
  @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id] 
end

def require_admin
  redirect_to '/login' unless current_admin
end

  protect_from_forgery with: :exception

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  
  before_action :require_admin
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:name, :description, :image, {gallery: []})
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token #, only: [:one_or_two_actions_here]


  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    respond_to do |format|

      format.html do
        if @message.valid?
          MessageMailer.new_message(@message).deliver_now
          redirect_to contact_sent_path
        else
          redirect_to contact_error_path
        end
      end

      format.js do
        if @message.valid?
          MessageMailer.new_message(@message).deliver_now
          flash.now[:notice] = "Üzenetét elküldtük!"
        else
          flash.now[:error]
        end
      end
    end

  end

  def contact_error

  end

  def contact_sent

  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		
	end

		def about
	end
	
	def reference	
		@houses = House.all
	end

  	def show
  		@houses = House.find(params[:id])
  	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	end

	def create
	  @admin = Admin.find_by_email(params[:session][:email])
	  if @admin && @admin.authenticate(params[:session][:password])
	    session[:admin_id] = @admin.id
	    redirect_to '/admin'
			NotifMailer.login_notif.deliver_now
	  else
	    redirect_to '/login'
	  end 
	end

	def destroy 
		session[:admin_id] = nil 
		redirect_to '/'	 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/houses/_admin_widget.html.erb
<div id="admin-widget">
<% if current_admin %> 
<div class="row">
<div class="col-sm-12">
<p class="pull-left a-info">
Bejelentkezve mint:<br>
<strong><%= current_admin.email %></strong>
</p>
<p class="pull-right ">
<%= link_to "", logout_path, method: "delete", class: 'fa fa-sign-out fa-2x a-logout-big' %>
</p>
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></li> 
  </ul> 
<% end %>
</div>
</div>
</div>
<hr>

app/views/houses/_form.html.erb
<div class="row">
<div class="col-sm-6">
<div class="row">
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div class="col-sm-12" id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group field col-sm-12">
    <%= f.label :name, class: 'control-label' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group field col-sm-12">
    <%= f.label :description, class: 'control-label' %><br>
    <%= f.text_area :description, class: 'form-control', rows: '5'  %>
  </div>
 <div class="form-group field col-sm-12">
    <%= f.label :image, class: 'control-label' %><br>
    <%= f.file_field :image %>
  </div>
   <div class="form-group field col-sm-12">
    <%= f.label :gallery, class: 'control-label' %><br>
    <%= f.file_field :gallery, multiple: true %>
  </div>
  <div class="col-sm-12">
    <%= f.submit class: 'btn btn-default pull-right' %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/houses/edit.html.erb
<%= render "houses/admin_widget" %>
<div class="row">
	<div class="col-sm-12">
		<%= link_to '', houses_path, class: 'pull-left fa fa-arrow-circle-o-left fa-2x a-back-big' %>
		<%= link_to '', @house, class: 'pull-right fa fa-eye fa-2x a-show-big' %>
	</div>
</div>
<h1>Editing House</h1>

<%= render 'form' %>

app/views/houses/index.html.erb
<%= render "houses/admin_widget" %>
<p id="notice"><%= notice %></p>
<h1>Listing Houses</h1>
<br>
<%= link_to 'Új épület hozzáadása', new_house_path %>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
    <th colspan="1"></th>
    <th>Image</th>
      <th>Name</th>
      
      <th>Description</th>
      
      
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
      <td>
        <%= link_to '', house, class: 'fa fa-eye fa-lg a-show-small' %>
        <%= link_to '', edit_house_path(house), class: 'fa fa-pencil-square-o fa-lg a-edit-small' %>
        <%= link_to '', house, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash fa-lg a-del-small' %>
        </td>
        <td  data-toggle="tooltip" data-placement="right" title="<%= house.image %>"><%= image_tag house.image.thumb.url %></td>
        <td><%= house.name %></td>
        
        <td><%= house.description %></td>
        
        
       
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/houses/new.html.erb
<%= render "houses/admin_widget" %>
<div class="row">
	<div class="col-sm-12">
		<%= link_to '', houses_path, class: 'pull-left fa fa-arrow-circle-o-left fa-2x a-back-big' %>
	</div>
</div>
<h1>New House</h1>
<%= render 'form' %>

app/views/houses/show.html.erb
<%= render "houses/admin_widget" %>
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-sm-12">
<%= link_to '', houses_path, class: 'pull-left fa fa-arrow-circle-o-left fa-2x a-back-big'%>
<%= link_to '', edit_house_path(@house), class: 'pull-right fa fa-pencil-square-o fa-2x a-edit-big' %>
</div>
</div>
<div class="col-sm-3 a-show-thumb">
 <%= image_tag @house.image.thumb.url %>
</div>
<div class="col-sm-9">
<p>
  <strong>Név:</strong>
  <%= @house.name %>
</p>

<p>
  <strong>Leírás:</strong>
  <%= @house.description %>
</p>
<p>
	<strong>Galéria:</strong><br>
	<% @house.gallery.each do |p| %>
  <%= image_tag p.thumb.url %>
<% end %>
</p>

</div>

app/views/layouts/_chevron_up.html.erb
<a href="#0" class="cd-top"><i class="fa fa-chevron-circle-up fa-4x"></i></a>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container" id="footer">
	<div class="row" id="footer-content" >
	<div class="col-xs-12 col-sm-4 col-md-4"><h3>Impresszum</h3><p>A portál szerkesztését és karbantartását Marton Attila végzi a www.csaladihazkivitelezes.com megbízásából.</p></div>
	<div class="col-xs-12 col-sm-4 col-md-4"><h3>Adatvédelem</h3><p>A CsaládiházKivitelezés oldal számára kiemelt fontosságú látogatói által rendelkezésre bocsátott személyes adatok védelme, a látogatók információs önrendelkezési jogának biztosítása. Cégünk elkötelezi magát a látogatók személyes adatainak oly módon történő kezelése mellett, amely a vonatkozó hatályos jogszabályoknak teljes körűen eleget téve járul hozzá a látogatók biztonságos internetezési lehetőségeinek megteremtéséhez</p></div>
	<div class="col-xs-12 col-sm-4 col-md-4">
      <h3>Kapcsolat</h3>
    <%= form_for Message.new, html: { remote: true }, url: contact_path do |message_form| %>
        <div class="row">
          <div class="field col-sm-12">
            <%= message_form.text_field :name, placeholder: "Név" %>
          </div>

          <div class="field col-sm-12">
            <%= message_form.email_field :email, placeholder: "Email"%>
          </div>

          <div class="field col-sm-12">
            <%= message_form.text_area :content, placeholder: "Üzenet"%>
          </div>
        </div>

        <div class="row">
          <div class="field col-sm-12">
            <%= message_form.submit "Küldés" %>
          </div>
        </div>
    <% end %>
	</div>
	</div>
	</div>
	</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="full-navbar">
<div class="container-fluid container" id="custom-navbar" >
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
       <%= link_to '',root_path, class: 'navbar-brand' %>
       </div>
	<div class="collapse navbar-collapse navbar-right" id="myNavbar">
	<ul class="nav navbar-nav">
	<li class="<%= 'active' if current_page?(root_path) %>"  id="navbar-box"><%= link_to 'Főoldal', root_path %></li>
	<li class="<%= 'active' if current_page?(about_path) %>"  id="navbar-box"><%= link_to 'Rólunk', about_path %></li>
	<li class="<%= 'active' if current_page?(references_path) %>"  id="navbar-box"><%= link_to 'Referencia', references_path %></li>
	</div>
</div>
</nav>

app/views/layouts/_rootcarousel.html.erb
<div class="zoomground-wrap">

  <div class="zoomground"></div>

  <div class="zoomground-logo-wrap"></div>

  <div id="jump-down-button">
    <a class="page-scroll fa fa fa-angle-double-down fa-4x" href="#content-wrap"></a>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Családiház kivitelezés</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', async: Rails.env.production?, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

<% if current_page?(root_path) %>
    <%= render 'layouts/rootcarousel' %>
<% end %>

<div class="container" id="content-wrap">
  <div  id="content">

    <%= yield %>

  </div>
</div>

<%= render "layouts/footer" %>

<%= render "layouts/chevron_up" %>

</body>
</html>

app/views/messages/contact_error.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1 class="text-center" ><span class="glyphicon glyphicon-alert center" ></span><br>Hiba lépett fel</h1>
    <p class="text-center" >Számítógépe valószínűleg nem támogatja a JavaScript technológiát</p>
    <p class="text-center" >Kérjük vegye fel velünk a kapcsolatot a martonattila66@gmail.com címen</p>
  </div>
</div>

app/views/messages/contact_sent.html.erb
<div class="row">
  <div class="col-sm-6">
<h1 class="text-center" >Köszönjük üzenetét</h1>
<p class="text-center" >Hamarosan keresni fogjuk...</p>
  </div>
</div>

app/views/messages/create.js.erb
<% if flash[:notice] %>
$('#new_message').before('<div class="notice"><%= flash[:notice] %></div>');
$('#errors').remove();
$('#new_message').remove();
<% end %>

<% if @message.errors.any? %>
$('#errors').remove();
$('#new_message').before('<div class="errors" id="errors"><% @message.errors.each do |attr,msg| %> <%= msg %> <br> <% end %></div>');

<% end %>

app/views/pages/about.html.erb
<h1>Rólunk</h1>

app/views/pages/index.html.erb
<div class="row" id="quote-block">
	<i class="fa fa-quote-right fa-1x col-sm-1 col-xs-3"></i>
  <p id="welcome" class="col-sm-11 col-xs-9">Művészetként tekintünk az építési folyamatokra. Hisszük hogy a telek a vásznat, partnereink pedig a művész képzeletét biztosítják számunkra. Mi vagyunk a kéz Ön számára, hogy álmai vászonra kerüljenek, és valósággá váljanak.</p>
</div>

app/views/pages/reference.html.erb
<h1>Referenciáink</h1></br>
<p>kérjük válasszon teljesített projektjeink közül egyet...</p>
    <ul class="row" id="reference-list">
      <% @houses.each do |house| %>
      <li class="col-sm-4">
      <%= link_to image_tag(house.image.cover.url, class: "img-responsive"),show_house_path(house) %>
      </li>
    <% end %>
    </ul>

app/views/pages/show.html.erb
<div class="show-cover" style="background-image:url(<%= @houses.image.url %>);">

	<div class="row" id="caption">
	<div class="col-xs-12 col-sm-2">
		
  <%= image_tag @houses.image.thumb.url %>
	</div>
	<div class="col-xs-12 col-sm-10">
  <strong><%= @houses.name %></strong>
  <br>
  <%= @houses.description %>
</div>

</div>
</div>
<hr>
	<div id="gallery">
	<ul class="row" id="lightGallery">
	<% @houses.gallery.each do |p| %>
	<li class="col-sm-4" data-src="<%= p.url %>">
  <%= image_tag p.cover.url, class: "img-responsive" %>
  </li>
<% end %>
</ul>
</div>